config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :recipes do
    resources :reviews
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:update, :destroy]
  before_action :require_user
  before_action :require_same_or_admin_user, only: [:update, :destroy]
  
  def new
   @recipe = Recipe.find(params[:recipe_id]) 
   @review = @recipe.reviews.new
  end
  
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.build(review_params)
    @review.chef = current_user
    if @review.save
      flash[:success] = "Your review was updated successfully"
      redirect_to recipe_path(@recipe)
    else
      flash[:danger] = "Sorry, there was an error saving your review"
      render 'new'
    end
  end
  
  def edit
    @review = Review.find(params[:id])
  end
  
  def update
    if @review.update(review_params)
      flash[:success] = "Your review was updated successfully"
      redirect_to recipe_path(@review.recipe)
    else
      render :edit
    end
  end
  
  def destroy
    @review.destroy
    flash[:success] = "Review Deleted"
    redirect_to recipe_path(params[:recipe_id])
  end
  
  private
  
    def review_params
      params.require(:review).permit(:body)
    end
    
    def set_review
      @review = Review.find(params[:id])
    end
    
    def require_same_or_admin_user
      if current_user != @review.chef && !current_user.admin?
        flash[:danger] = "You can only upate/delete comments if you created the comment or are an administrator"
      end
    end
end

app/views/reviews/_form.html.erb
<%= render 'shared/errors', obj: @review %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for ([@recipe, @review]) do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 10 %>
      <%= f.submit(@review.new_record? ? 'Add Review' : 'Update Review', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/reviews/_review.html.erb
<div class="well">
 <%= link_to gravatar_for(review.chef, size: 60), chef_path(@recipe.chef), class: "pull-left" %>
 <div class="review">
  <h3><%= review.chef.chefname %></h3>
  <p>
  <%= simple_format(review.body) %>
  </p>
  <div>
   <% if logged_in? and current_user == review.chef %>
    <%= link_to "Update Review", edit_recipe_review_path(@recipe.id, review), class: "btn btn-default btn-info btn-small" %>
   <% end %>
   <% if logged_in? and (review.chef == current_user or current_user.admin?) %>
    <%= link_to "Delete Review", recipe_review_path(@recipe.id, review), method: :delete, class: "btn btn-default btn-danger btn-small", data: { confirm: "Are you sure?" } %>
   <% end %>
  </div>
 </div>
</div>

app/views/reviews/edit.html.erb
<%= render 'shared/page_title', title: "Write a Review" %>

<%= render 'form' %>

app/views/reviews/new.html.erb
<%= render 'shared/page_title', title: "Write a Review" %>

<%= render 'form' %>